### ISSUE TITLE
Sort polygons by area

### ISSUE THREAD

**Issue by awoodruff** [axismaps/bcworkshop-server#7]
On the services map, I think in a few cases small enclave neighborhoods are being layered underneath their enclosing neighbor, so you can't click on them. For example I can't seem to get to the small polygon in the middle here:
![screen shot 2015-03-18 at 11 29 13 am](https://cloud.githubusercontent.com/assets/3533462/6712321/536605bc-cd62-11e4-9397-8137f3b2bec7.png)

Is there some way here on the back end to sort these by area?

**Comment by davidheyman** [comment]
@kingfisher13 Let's add an area column to the DB table instead of calculating on every query.

**Comment by kingfisher13** [comment]
Still having issues on the services map with overlapping polygons.

**Comment by kingfisher13** [comment]
Nevermind. I was on the wrong branch.
